package com.meteoru.fragdetails;

public class SuperHeroInfo {
    public static final String[] NAMES = { "Batman", "Aquaman", "Superman", "Hulk", "Flash"};
    public static final String[] HISTORY = { "Bruce Wayne, having witnessed the murder of his parents as a child, he swore revenge on criminals, an oath tempered with a sense of justice. Wayne trains himself both physically and intellectually and dons a bat-themed costume to fight crime. Batman operates in the fictional Gotham City, assisted by various supporting characters including his butler Alfred Pennyworth, his crime-fighting partner Robin, the police commissioner Jim Gordon, and occasionally the heroine Batgirl. He fights a large assortment of villains, often referred to as the \"rogues gallery,\" which includes the Joker, the Penguin, the Riddler, Catwoman, Mr. Freeze, Two-Face, Ra's al Ghul, Scarecrow, Poison Ivy, and Clayface. Unlike most superheroes, he does not possess any superpowers; he makes use of intellect, detective skills, science and technology, wealth, physical prowess, martial arts skills, an indomitable will, fear, and intimidation in his continuous war on crime..",
            "Aquaman is a superhero appearing in comic book titles by DC Comics. Created by Paul Norris and Mort Weisinger, the character debuted in More Fun Comics #73 (November 1941).[1] Initially a backup feature in DC's anthology titles, Aquaman later starred in several volumes of a solo title. During the late 1950s and 1960s superhero-revival period known as the Silver Age, he was a founding member of the Justice League of America. In the 1990s Modern Age, Aquaman's character became more serious than in most previous interpretations, with storylines depicting the weight of his role as king of Atlantis.",
            "Superman was born Kal-El on the planet Krypton, before being rocketed to Earth as an infant by his scientist father Jor-El, moments before Krypton's destruction. Discovered and adopted by a Kansas farmer and his wife, the child is raised as Clark Kent and imbued with a strong moral compass. Very early on he started to display superhuman abilities, which, upon reaching maturity, he resolved to use for the benefit of humanity. Superman resides and operates in the fictional American city of Metropolis. As Clark Kent, he is a journalist for the Daily Planet, a Metropolis newspaper. Superman's primary love interest is Lois Lane and his archenemy is supervillain Lex Luthor.[11]",
            "was created by Stan Lee and Jack Kirby, and first appeared in The Incredible Hulk #1 (May 1962). Throughout his comic book appearances, the Hulk is portrayed as a large green humanoid that possesses near limitless superhuman strength and great invulnerability, attributes that grow more potent the angrier he becomes. Hulk is the alter ego of Bruce Banner, a socially withdrawn and emotionally reserved physicist who physically transforms into the Hulk under emotional stress and other specific circumstances at will or against it; these involuntary transformations lead to many complications in Banner's life. When transformed, the Hulk often acts as a disassociated personality separate from Banner. Over the decades of Hulk stories, the Hulk has been represented with several personalities based on Hulk and Banner's fractured psyche, ranging from mindless savage to brilliant warrior, and Banner has taken control of the Hulk's form on occasion. Banner first transforms into the Hulk after being caught in the blast of the gamma bomb he invented while saving Rick Jones, a youth who had wandered onto the testing range.",
            "Nicknamed the Scarlet Speedster, the \"Crimson Comet\" and \"The Blur\", all incarnations of the Flash possess \"super speed\", which includes the ability to run and move extremely fast, use superhuman reflexes, and seemingly violate certain laws of physics. Thus far, four different characters—each of whom somehow gained the power of \"super-speed\"—have assumed the identity of the Flash: Jay Garrick (1940–present), Barry Allen (1956–1985, 2008–present), Wally West (1986–2006, 2007–2012, 2013–present), and Bart Allen (2006–2007). Before Wally and Bart's ascension to the mantle of the Flash, they were both Flash protégés under the same name Kid Flash (Bart was also known as Impulse)." };

}
